language: csharp
dist: trusty
mono: none
dotnet: 3.0
script:
  - dotnet restore src/coreDox/coreDox.csproj
  - dotnet restore src/Targets/coreDox.Target.Html/src/coreDox.Target.Html.csproj
  - dotnet restore tests/coreDox.Core.Tests/coreDox.Core.Tests.csproj
  - dotnet build src/coreDox/coreDox.csproj
  - dotnet build src/Targets/coreDox.Target.Html/src/coreDox.Target.Html.csproj
  - mkdir -p tests/coreDox.Core.Tests/bin/Debug/netcoreapp2.0/Targets/Html
  - cp tests/coreDox.Core.Tests/Targets/Html/* tests/coreDox.Core.Tests/bin/Debug/netcoreapp2.0/Targets/Html/
  - dotnet test tests/coreDox.Core.Tests/coreDox.Core.Tests.csproj