language: csharp
dist: trusty
sudo: required
mono: none
before_script:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update -qq
  - sudo apt-get install dotnet-dev-1.0.1
script:
  - dotnet restore src/coreDox/coreDox.csproj
  - dotnet restore tests/coreDox.Tests/coreDox.Tests.csproj
  - dotnet test tests/coreDox.Tests/coreDox.Tests.csproj
  - dotnet build src/coreDox/coreDox.csproj