language: csharp
dist: trusty
mono: none
dotnet: 2.1.4
script:
  - dotnet restore src/coreDox/coreDox.csproj
  - dotnet restore src/[Exporter]/coreDox.Exporter.Html/coreDox.Exporter.Html.csproj
  - dotnet restore tests/coreDox.Core.Tests/coreDox.Core.Tests.csproj
  - dotnet build src/coreDox/coreDox.csproj
  - dotnet build src/[Exporter]/coreDox.Exporter.Html/coreDox.Exporter.Html.csproj
  - mkdir -p tests/coreDox.Core.Tests/bin/Debug/netcoreapp2.0/Exporter/Html
  - mkdir -p tests/coreDox.Core.Tests/bin/Debug/netcoreapp2.0/[TestAssemblies]
  - cp tests/coreDox.Core.Tests/\[TestAssemblies\]/* tests/coreDox.Core.Tests/bin/Debug/netcoreapp2.0/\[TestAssemblies\]/
  - cp tests/coreDox.Core.Tests/Exporter/Html/* tests/coreDox.Core.Tests/bin/Debug/netcoreapp2.0/Exporter/Html/
  - dotnet test tests/coreDox.Core.Tests/coreDox.Core.Tests.csproj