using coreDox.Core.Contracts;
using System.Collections.Generic;

namespace coreDox.Core.CodeModel.Base
{
    public abstract class DoxCodeModel
    {
        /// <summary>
        /// The name of the code element.
        /// </summary>
        public string Name { get; protected set; }

        /// <summary>
        /// The full name of the code element.
        /// </summary>
        public string FullName { get; protected set; }

        /// <summary>
        /// The list of all models generated by the registered <see cref="IModelProvider"/>s.
        /// </summary>
        public Dictionary<string, object> Models { get; } = new Dictionary<string, object>();
    }
}
